# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0002_auto_20160825_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
