# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0006_auto_20161003_0935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attack',
            unique_together=set([('date', 'description')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'country')]),
        ),
    ]
