# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0008_attack_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='location',
        ),
    ]
