# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0009_remove_attack_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attack',
            unique_together=set([('date', 'description', 'num_injured', 'num_dead')]),
        ),
    ]
