# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0010_auto_20161013_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='attacks.Location'),
        ),
    ]
